Updated makefile memory compare checks

diff --git a/hardware/simul/verilator/Makefile b/hardware/simul/verilator/Makefile
--- a/hardware/simul/verilator/Makefile
+++ b/hardware/simul/verilator/Makefile
@@ -4,12 +4,25 @@ RTL_TOP?= RISCV_core
 FLAGS = -Wall --trace
 HEX_PROG?=lower_upper_byte
 CXXFLAGS= -DTB_INIT_FILE='\"$(HEX_SRC_PATH)/$(HEX_PROG).inst\"'
+
 all: clean compile build run
+
+check_all: clean check_mem_dump compare_files
 
 check_mem_dump: clean hex_gen compile build run
 	cd simulation_model && g++ -DTB_INIT_FILE=\"../$(HEX_SRC_PATH)/$(HEX_PROG).inst\" -o prog BRISKI_simulator.cpp 
 	cd simulation_model && ./prog
-	vimdiff rtl_memory.txt simulation_model/memory.txt
+
+compare_files:
+	diff rtl_memory.txt simulation_model/memory.txt
+	@if [ $$? -eq 0 ]; then \
+		echo "OK: Contents of RTL Memory and Software model Memory Files are identical."; \
+	elif [ $$? -eq 1 ]; then \
+		echo "ERROR: Contents of RTL Memory and Software model Memory Files are different. use vimdiff to check differences"; \
+	else \
+		echo "FATAL: An error occurred while comparing files."; \
+	fi
+
 hex_gen:
 	cd $(HEX_SRC_PATH) && cd ../ && PROG=$(HEX_PROG) $(MAKE) hex_gen 
 compile:
